name: sge_app
description: "SGE - Sistema de Geolocalización de Empleados"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  http: ^1.2.0
  provider: ^6.1.0
  shared_preferences: ^2.3.0
  mapbox_maps_flutter: ^2.9.0
  geolocator: ^13.0.2
  permission_handler: ^11.3.0
  flutter_background_service: ^5.1.0
  flutter_local_notifications: ^18.0.1
  sqflite: ^2.4.3
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo-megaservicios.png
