CREATE EXTENSION IF NOT EXISTS postgis;
CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE EXTENSION IF NOT EXISTS postgis;

CREATE TABLE "Departamentos" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nombre" text NOT NULL,
    CONSTRAINT "PK_Departamentos" PRIMARY KEY ("Id")
);

CREATE TABLE "EstadosAlerta" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Codigo" text NOT NULL,
    "Descripcion" text NOT NULL,
    CONSTRAINT "PK_EstadosAlerta" PRIMARY KEY ("Id")
);

CREATE TABLE "Roles" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nombre" text NOT NULL,
    CONSTRAINT "PK_Roles" PRIMARY KEY ("Id")
);

CREATE TABLE "LugaresTrabajo" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nombre" text NOT NULL,
    "Direccion" text NOT NULL,
    "Descripcion" text,
    "Geocerca" geometry NOT NULL,
    "Activo" boolean NOT NULL,
    "FechaCreacion" timestamp with time zone NOT NULL,
    "DepartamentoId" integer NOT NULL,
    CONSTRAINT "PK_LugaresTrabajo" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_LugaresTrabajo_Departamentos_DepartamentoId" FOREIGN KEY ("DepartamentoId") REFERENCES "Departamentos" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "Empleados" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Paterno" text NOT NULL,
    "Materno" text NOT NULL,
    "Nombres" text NOT NULL,
    "Ci" text NOT NULL,
    "Usuario" text NOT NULL,
    "PasswordHash" text NOT NULL,
    "Telefono" text NOT NULL,
    "LugarTrabajoActualId" integer,
    "IdRol" integer NOT NULL,
    "Activo" boolean NOT NULL,
    "FechaCreacion" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Empleados" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Empleados_LugaresTrabajo_LugarTrabajoActualId" FOREIGN KEY ("LugarTrabajoActualId") REFERENCES "LugaresTrabajo" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_Empleados_Roles_IdRol" FOREIGN KEY ("IdRol") REFERENCES "Roles" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "AlertasGeocerca" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "EmpleadoId" integer NOT NULL,
    "EstadoAlertaId" integer NOT NULL,
    "FechaHora" timestamp with time zone NOT NULL,
    "Observaciones" text,
    CONSTRAINT "PK_AlertasGeocerca" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AlertasGeocerca_Empleados_EmpleadoId" FOREIGN KEY ("EmpleadoId") REFERENCES "Empleados" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_AlertasGeocerca_EstadosAlerta_EstadoAlertaId" FOREIGN KEY ("EstadoAlertaId") REFERENCES "EstadosAlerta" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "HistorialLugaresTrabajo" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "EmpleadoId" integer NOT NULL,
    "LugarTrabajoId" integer NOT NULL,
    "FechaCambio" timestamp with time zone NOT NULL,
    "Observaciones" text,
    CONSTRAINT "PK_HistorialLugaresTrabajo" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_HistorialLugaresTrabajo_Empleados_EmpleadoId" FOREIGN KEY ("EmpleadoId") REFERENCES "Empleados" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_HistorialLugaresTrabajo_LugaresTrabajo_LugarTrabajoId" FOREIGN KEY ("LugarTrabajoId") REFERENCES "LugaresTrabajo" ("Id") ON DELETE CASCADE
);

CREATE TABLE "JornadasTrabajo" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "EmpleadoId" integer NOT NULL,
    "Fecha" timestamp with time zone NOT NULL,
    "HoraEntrada" timestamp with time zone,
    "HoraSalida" timestamp with time zone,
    "TotalHoras" numeric,
    "Estado" character varying(20) NOT NULL,
    "TiempoFueraGeocerca" integer NOT NULL,
    "AlertasGeneradas" integer NOT NULL,
    CONSTRAINT "PK_JornadasTrabajo" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_JornadasTrabajo_Empleados_EmpleadoId" FOREIGN KEY ("EmpleadoId") REFERENCES "Empleados" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Ubicaciones" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "EmpleadoId" integer NOT NULL,
    "UbicacionEmp" geometry NOT NULL,
    "FechaHora" timestamp with time zone NOT NULL,
    "EstaEnGeocerca" boolean,
    CONSTRAINT "PK_Ubicaciones" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Ubicaciones_Empleados_EmpleadoId" FOREIGN KEY ("EmpleadoId") REFERENCES "Empleados" ("Id") ON DELETE CASCADE
);

CREATE TABLE "RegistrosAsistencia" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "EmpleadoId" integer NOT NULL,
    "TipoRegistro" character varying(10) NOT NULL,
    "FechaHora" timestamp with time zone NOT NULL,
    "UbicacionId" integer,
    "EsAutomatico" boolean NOT NULL,
    "Observaciones" text,
    "Verificado" boolean NOT NULL,
    CONSTRAINT "PK_RegistrosAsistencia" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_RegistrosAsistencia_Empleados_EmpleadoId" FOREIGN KEY ("EmpleadoId") REFERENCES "Empleados" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_RegistrosAsistencia_Ubicaciones_UbicacionId" FOREIGN KEY ("UbicacionId") REFERENCES "Ubicaciones" ("Id") ON DELETE SET NULL
);

CREATE INDEX "IX_AlertasGeocerca_EmpleadoId" ON "AlertasGeocerca" ("EmpleadoId");

CREATE INDEX "IX_AlertasGeocerca_EstadoAlertaId" ON "AlertasGeocerca" ("EstadoAlertaId");

CREATE INDEX "IX_AlertasGeocerca_FechaHora" ON "AlertasGeocerca" ("FechaHora" DESC);

CREATE UNIQUE INDEX "IX_Empleados_Ci" ON "Empleados" ("Ci");

CREATE INDEX "IX_Empleados_IdRol" ON "Empleados" ("IdRol");

CREATE INDEX "IX_Empleados_LugarTrabajoActualId" ON "Empleados" ("LugarTrabajoActualId");

CREATE UNIQUE INDEX "IX_Empleados_Usuario" ON "Empleados" ("Usuario");

CREATE INDEX "IX_HistorialLugaresTrabajo_EmpleadoId" ON "HistorialLugaresTrabajo" ("EmpleadoId");

CREATE INDEX "IX_HistorialLugaresTrabajo_FechaCambio" ON "HistorialLugaresTrabajo" ("FechaCambio" DESC);

CREATE INDEX "IX_HistorialLugaresTrabajo_LugarTrabajoId" ON "HistorialLugaresTrabajo" ("LugarTrabajoId");

CREATE UNIQUE INDEX "IX_JornadasTrabajo_EmpleadoId_Fecha" ON "JornadasTrabajo" ("EmpleadoId", "Fecha");

CREATE INDEX "IX_JornadasTrabajo_Fecha" ON "JornadasTrabajo" ("Fecha" DESC);

CREATE INDEX "IX_LugaresTrabajo_DepartamentoId" ON "LugaresTrabajo" ("DepartamentoId");

CREATE INDEX "IX_LugaresTrabajo_Geocerca" ON "LugaresTrabajo" USING GIST ("Geocerca");

CREATE INDEX "IX_RegistrosAsistencia_EmpleadoId" ON "RegistrosAsistencia" ("EmpleadoId");

CREATE INDEX "IX_RegistrosAsistencia_FechaHora" ON "RegistrosAsistencia" ("FechaHora" DESC);

CREATE INDEX "IX_RegistrosAsistencia_TipoRegistro" ON "RegistrosAsistencia" ("TipoRegistro");

CREATE INDEX "IX_RegistrosAsistencia_UbicacionId" ON "RegistrosAsistencia" ("UbicacionId");

CREATE INDEX "IX_Ubicaciones_EmpleadoId" ON "Ubicaciones" ("EmpleadoId");

CREATE INDEX "IX_Ubicaciones_FechaHora" ON "Ubicaciones" ("FechaHora" DESC);

CREATE INDEX "IX_Ubicaciones_UbicacionEmp" ON "Ubicaciones" USING GIST ("UbicacionEmp");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251207140642_TablasInicialesALFINNNN', '9.0.11');

COMMIT;

