// <auto-generated />
using System;
using MapboxMegaservicios.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MapboxMegaservicios.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260615134107_AgregarMigracionPendiente")]
    partial class AgregarMigracionPendiente
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EstadoAlerta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("EstadosAlerta");
                });

            modelBuilder.Entity("MapboxMegaservicios.API.Models.AlertaGeocerca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("integer")
                        .HasColumnName("EmpleadoId");

                    b.Property<int>("EstadoAlertaId")
                        .HasColumnType("integer")
                        .HasColumnName("EstadoAlertaId");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EmpleadoId");

                    b.HasIndex("EstadoAlertaId");

                    b.HasIndex("FechaHora")
                        .IsDescending();

                    b.ToTable("AlertasGeocerca", (string)null);
                });

            modelBuilder.Entity("MapboxMegaservicios.API.Models.Departamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Departamentos");
                });

            modelBuilder.Entity("MapboxMegaservicios.API.Models.Empleado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Ci")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdRol")
                        .HasColumnType("integer");

                    b.Property<int?>("LugarTrabajoActualId")
                        .HasColumnType("integer")
                        .HasColumnName("LugarTrabajoActualId");

                    b.Property<string>("Materno")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Paterno")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Ci")
                        .IsUnique();

                    b.HasIndex("IdRol");

                    b.HasIndex("LugarTrabajoActualId");

                    b.HasIndex("Usuario")
                        .IsUnique();

                    b.ToTable("Empleados", (string)null);
                });

            modelBuilder.Entity("MapboxMegaservicios.API.Models.HistorialLugarTrabajo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("integer")
                        .HasColumnName("EmpleadoId");

                    b.Property<DateTime>("FechaCambio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LugarTrabajoId")
                        .HasColumnType("integer")
                        .HasColumnName("LugarTrabajoId");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EmpleadoId");

                    b.HasIndex("FechaCambio")
                        .IsDescending();

                    b.HasIndex("LugarTrabajoId");

                    b.ToTable("HistorialLugaresTrabajo", (string)null);
                });

            modelBuilder.Entity("MapboxMegaservicios.API.Models.JornadaTrabajo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AlertasGeneradas")
                        .HasColumnType("integer");

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("integer");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("HoraEntrada")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("HoraSalida")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TiempoFueraGeocerca")
                        .HasColumnType("integer");

                    b.Property<decimal?>("TotalHoras")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("Fecha")
                        .IsDescending();

                    b.HasIndex("EmpleadoId", "Fecha")
                        .IsUnique();

                    b.ToTable("JornadasTrabajo", (string)null);
                });

            modelBuilder.Entity("MapboxMegaservicios.API.Models.LugarTrabajo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<int>("DepartamentoId")
                        .HasColumnType("integer");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Polygon>("Geocerca")
                        .HasColumnType("geometry");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DepartamentoId");

                    b.HasIndex("Geocerca");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Geocerca"), "GIST");

                    b.ToTable("LugaresTrabajo", (string)null);
                });

            modelBuilder.Entity("MapboxMegaservicios.API.Models.RegistroAsistencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("integer");

                    b.Property<bool>("EsAutomatico")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text");

                    b.Property<string>("TipoRegistro")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int?>("UbicacionId")
                        .HasColumnType("integer");

                    b.Property<bool>("Verificado")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("EmpleadoId");

                    b.HasIndex("FechaHora")
                        .IsDescending();

                    b.HasIndex("TipoRegistro");

                    b.HasIndex("UbicacionId");

                    b.ToTable("RegistrosAsistencia", (string)null);
                });

            modelBuilder.Entity("MapboxMegaservicios.API.Models.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("MapboxMegaservicios.API.Models.Ubicacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("integer")
                        .HasColumnName("EmpleadoId");

                    b.Property<bool?>("EstaEnGeocerca")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsPossibleSpoofing")
                        .HasColumnType("boolean");

                    b.Property<Point>("UbicacionEmp")
                        .IsRequired()
                        .HasColumnType("geometry");

                    b.HasKey("Id");

                    b.HasIndex("EmpleadoId");

                    b.HasIndex("FechaHora")
                        .IsDescending();

                    b.HasIndex("UbicacionEmp");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("UbicacionEmp"), "GIST");

                    b.ToTable("Ubicaciones", (string)null);
                });

            modelBuilder.Entity("MapboxMegaservicios.API.Models.AlertaGeocerca", b =>
                {
                    b.HasOne("MapboxMegaservicios.API.Models.Empleado", "Empleado")
                        .WithMany("Alertas")
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EstadoAlerta", "EstadoAlerta")
                        .WithMany("Alertas")
                        .HasForeignKey("EstadoAlertaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empleado");

                    b.Navigation("EstadoAlerta");
                });

            modelBuilder.Entity("MapboxMegaservicios.API.Models.Empleado", b =>
                {
                    b.HasOne("MapboxMegaservicios.API.Models.Rol", "Rol")
                        .WithMany("Empleados")
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MapboxMegaservicios.API.Models.LugarTrabajo", "LugarTrabajoActual")
                        .WithMany("Empleados")
                        .HasForeignKey("LugarTrabajoActualId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("LugarTrabajoActual");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("MapboxMegaservicios.API.Models.HistorialLugarTrabajo", b =>
                {
                    b.HasOne("MapboxMegaservicios.API.Models.Empleado", "Empleado")
                        .WithMany("HistorialLugaresTrabajo")
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MapboxMegaservicios.API.Models.LugarTrabajo", "LugarTrabajo")
                        .WithMany("Historial")
                        .HasForeignKey("LugarTrabajoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empleado");

                    b.Navigation("LugarTrabajo");
                });

            modelBuilder.Entity("MapboxMegaservicios.API.Models.JornadaTrabajo", b =>
                {
                    b.HasOne("MapboxMegaservicios.API.Models.Empleado", "Empleado")
                        .WithMany()
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("MapboxMegaservicios.API.Models.LugarTrabajo", b =>
                {
                    b.HasOne("MapboxMegaservicios.API.Models.Departamento", "Departamento")
                        .WithMany("LugaresTrabajo")
                        .HasForeignKey("DepartamentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Departamento");
                });

            modelBuilder.Entity("MapboxMegaservicios.API.Models.RegistroAsistencia", b =>
                {
                    b.HasOne("MapboxMegaservicios.API.Models.Empleado", "Empleado")
                        .WithMany()
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MapboxMegaservicios.API.Models.Ubicacion", "Ubicacion")
                        .WithMany()
                        .HasForeignKey("UbicacionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Empleado");

                    b.Navigation("Ubicacion");
                });

            modelBuilder.Entity("MapboxMegaservicios.API.Models.Ubicacion", b =>
                {
                    b.HasOne("MapboxMegaservicios.API.Models.Empleado", "Empleado")
                        .WithMany("Ubicaciones")
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("EstadoAlerta", b =>
                {
                    b.Navigation("Alertas");
                });

            modelBuilder.Entity("MapboxMegaservicios.API.Models.Departamento", b =>
                {
                    b.Navigation("LugaresTrabajo");
                });

            modelBuilder.Entity("MapboxMegaservicios.API.Models.Empleado", b =>
                {
                    b.Navigation("Alertas");

                    b.Navigation("HistorialLugaresTrabajo");

                    b.Navigation("Ubicaciones");
                });

            modelBuilder.Entity("MapboxMegaservicios.API.Models.LugarTrabajo", b =>
                {
                    b.Navigation("Empleados");

                    b.Navigation("Historial");
                });

            modelBuilder.Entity("MapboxMegaservicios.API.Models.Rol", b =>
                {
                    b.Navigation("Empleados");
                });
#pragma warning restore 612, 618
        }
    }
}
